{
	"extracts":[
		{	
			"extractId":"e_id",
			"datasource":{
				"url":"jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai",
				"driverClassName":"com.mysql.cj.jdbc.Driver",
				"username":"root",
				"password":"root",
				"table":"bend_info",
				"fields":[
					"bend_id",
					"bend_info_bending_len"
				]
			}
		}
	],
	"transfers":[
		{
			"stepId":"s_id",
			"extractId":"",
			"action":"sum",
			"fields":[
				"age"
			]
		},
		{
			"stepId":"s_id2",
			"extractId":"",
			"action":"add",
			"fields":[
				"desc"
			]
		}
	],
	"loads":[
		{
			"lastOperatorId":"s_id",
			"loadId":"load_id",
			"datasource":{
				"url":"jdbc:mysql://10.129.4.178:3307/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai",
				"driverClassName":"com.mysql.cj.jdbc.Driver",
				"username":"beacon",
				"password":"beacon",
				"table":"etl_demo",
				"fields":[
					"name",
					"age",
					"desc"
				]
			}
		}
	]
}